### ISSUE TITLE
Kubernetes specific AnnoationLabels for PVC under metadata

### ISSUE THREAD

**Issue by haarchri** [ballerinax/kubernetes#158]
**Description:**
We need Kubernetes specific Annotation Lables for PVCs like:

```
metadata:
  name: ballerina
  annotations:
     volume.beta.kubernetes.io/storage-class: 'efs'
```

because otherwise we are unable to provision pvcs in our environment
