### ISSUE TITLE
Kubernetes:Deployment configuration to read secrets thru env vars

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerinax/kubernetes#184]
**Description:**
Deployment annotation's env property should support generating the following env variables (to read value from secrets). 

```
env:
    - name: ecomm_backend_refund_sftp_username
      valueFrom:
        secretKeyRef:
            name: ecomm-back-end-sftp-secret
            key: username 
    - name: ecomm_backend_refund_sftp_password
      valueFrom:
        secretKeyRef:
            name: ecomm-back-end-sftp-secret
            key: password 
```

Mail thread - https://groups.google.com/forum/#!topic/ballerina-dev/hKsNkqbKNa8
