### ISSUE TITLE
Annotations support

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerinax/kubernetes#205]
**Description:**
Need to be able to add annotations using Kuberneted:Deployment annotation, like below. 

```
spec:
  replicas: 1
  template:
    metadata:
      annotations:
       prometheus.io/scrape: "true"
       prometheus.io/path: /metrics
       prometheus.io/port: "9797"
```
