### ISSUE TITLE
Should be able to define container ports

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerinax/kubernetes#206]
**Description:**
Currently container ports are defined from Service annotations. Ballerina core exposes some ports (e.g Prometheus) for which we don't have an endpoint defined in our ballerina program (hence we can't define service annotations). So we should be able to define these kind of ports in Kubernetes:Deployment annotation.

**Comment by raj-rajaratnam** [comment]
Similarly, Service annotation should support defining multiple ports. Should be able to generate following service yaml where prometheus port is exposed by ballerina core. 

```
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "order-data-service"
  name: "order-data-service-service"
  namespace: "default"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 8280
    name: http
  - port: 9797
    name: prometheus                 
  selector:
    app: "order-data-service"
  type: "LoadBalancer"
```
