### ISSUE TITLE
Improve Liveness Probe fields

### ISSUE THREAD

**Issue by hemikak** [ballerinax/kubernetes#288]
**Description:**
Currently to configure the liveness probe of a deployment, it takes multiple fields in the @kubernetes:Deployment{} annotation. This can be optimized to be a single field named `livenessProbe` which can have the value of a boolean or a record which has the configuration of a probe. Default values are used when using a `true` boolean value. Example:

```ballerina
@kubernetes:Deployment: {
    livenessProbe: true
}
```

This outputs to the following:
```yaml
    livenessProbe:
        initialDelaySeconds: 10  // default, as per current implementation.
        periodSeconds: 5  // default, as per current implementation.
        tcpSocket:
            port: 9090   // defaults to the ballerina service port.
```

The above values can be altered as follows if needed:
```ballerina
@kubernetes:Deployment: {
    livenessProbe: {
        port: 9090, // optional field, defaults to ballerina service port.
        initialDelaySeconds: 15, // optional field, default is 10.
        periodSeconds: 10 // optional field, default is 5.
    }
}
```
